apiVersion: v2
name: ska-mid-dish-b5dc-proxy
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://gitlab.com/ska-telescope/ska-mid-dish-b5dc-proxy/
icon: http://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
sources:
  - https://gitlab.com/ska-telescope/ska-mid-dish-b5dc-proxy/
maintainers:
  - name: Johan Venter
    email: jventer@sarao.ac.za
  - name: Samuel Twum
    email: samuel.twum@skao.int
  - name: Phelokazi dube
    email: pdube@sarao.ac.za
  - name: Abednigo Lethole
    email: alethole@sarao.ac.za
  - name: Barbara Ojur
    email: bojur@sarao.ac.za
  - name: Devon Petrie
    email: dpetrie@sarao.ac.za
  - name: Umkhulu Silere
    email: usilere@sarao.ac.za
  - name: Mpumelelo Nzama
    email: mnzama@sarao.ac.za
  - name: Yashren Reddi
    email: yreddi@sarao.ac.za  
dependencies:
  - name: ska-tango-util
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-base
    version: 0.4.15
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-base.enabled
  - name: ska-mid-dish-simulators
    version: 4.2.3
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-mid-dish-simulators.enabled

