enabled: true

system: SW-infrastructure
subsystem: ska-dish-lmc
telescope: SKA-mid

labels:
  app: ska-mid-dish-b5dc-manager

ska-tango-base:
  enabled: false

global:
  minikube: false
  operator: false
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"

  dishes: ["001"]

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent

b5dcmanager:
  image:
    registry: artefact.skao.int
    image: ska-mid-dish-b5dc-proxy
    tag: 0.0.1
    pullPolicy: IfNotPresent
  host:
  port:

deviceServers:
  dsmanager:
    file: "data/ds_manager.yaml"
    enabled: true

