{{ $localchart := . }}

{{- $lengthdishes := len .Values.global.dishes }}
{{- $lengthfqdns := len .Values.b5dcproxy.fqdns }}

{{- if ne $lengthfqdns 0 }}
    {{- if ne $lengthdishes $lengthfqdns }}
        {{- fail (printf "global.dishes (%d) and deviceServers.fqdns (%d) must have the same length when fqdns are specified" $lengthdishes $lengthfqdns ) }}
    {{- end }}
{{- end }}

{{- range $key, $deviceserver := .Values.deviceServers }}

{{ if $deviceserver.enabled }}

{{- $filedeviceserver := tpl ($.Files.Get $deviceserver.file) $ | fromYaml }}

{{- $_ := set $filedeviceserver "instances" ($localchart.Values.global.dishes | toStrings) }}
{{- $context := dict "name" $key "deviceserver" $filedeviceserver "image" $deviceserver.image "local" $localchart }}

{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }} 

{{- end }} # if enabled

{{- end }} # deviceservers
